Copyright (c) 2019 OERCompBiomed

# SciPy

[**SciPy**](https://scipy.org) is 

**You are encouraged to experiment with all our code!**

NOTE: The original notebook on Github might change over the time, and we recommend that you make a copy of our notebooks before you are editing them. In this respect you might adopt the naming convention my_<'name_of_notebook'>.ipynb, e.g. my_1.4-scipy-basics.ipynb

### Essential Libraries and Tools

In [9]:
import numpy as np
import pandas as pd

In [10]:
%matplotlib inline
import matplotlib.pyplot as plt

#### Versions:

In [11]:
print("NumPy version:", np.__version__)
print("pandas version:", pd.__version__)

import sys
print("Python version:", sys.version)

import matplotlib
print("matplotlib version:", matplotlib.__version__)

import scipy as sp
print("SciPy version:", sp.__version__)

import IPython
print("IPython version:", IPython.__version__)

NumPy version: 1.16.4
pandas version: 0.24.2
Python version: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
matplotlib version: 3.1.0
SciPy version: 1.2.1
IPython version: 7.6.1


#### SciPy sparse matrices

In [12]:
from scipy import sparse

# Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)
print("NumPy array:\n", eye)

# Convert the NumPy array to a SciPy sparse matrix in CSR format
# Only the nonzero entries are stored
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n", sparse_matrix)
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n", eye_coo)

NumPy array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
COO representation:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
